### ISSUE TITLE
missing semicolons

### ISSUE THREAD

**Issue by Skye-Smith** [trueshiba/CS120-demo#11]
missing semicolons on lines 14 and 18 of datetime_convert.cc

expected behavior: the program runs

actual behavior: program throws error on line 14 & 18

OS: Windows 10
Browser: firefox

possible solutions: add the required semicolons on lines 14 and 18

priority: high, program cannot run without solving the issue

reproducibility: always an issue, 100% reproducible

impact: high, program cannot run with bug in program

**Comment by trueshiba** [comment]
FIXED: I added 2 semicolons 👍
