### ISSUE TITLE
datetime_convert.java extra t

### ISSUE THREAD

**Issue by agilpatr** [trueshiba/CS120-demo#15]
In line 12 there is an extra t in formattedDate, breaking it.

Steps to Reproduce
Add an extra t.

Expected Behavior A clear and concise description of what you expected to happen.
I expected it to print out the formatted date.

Actual Behavior A clear and concise description of what actually happened.
The program broke because the called string does not exist.

Screenshots If applicable, add screenshots to help explain the issue/bug.

Possible Solution If you have any suggestions for a possible solution, please include them here.
Remove the extra t.

Related Issues Are there any related issues? If so, please link to them here.
Nope.

Priority How critical is this issue/bug? Low, medium, or high priority?
Medium priority, it will not run until it's fixed.

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
Easily, extra letters are common.

Impact What is the impact of this issue/bug? Low, medium, or high?**
High, it currently won't run.

**Comment by mishwilso** [comment]
Extermination Complete, the t has been removed
