### ISSUE TITLE
rgb_to_hex.py Extra Semicolons

### ISSUE THREAD

**Issue by agilpatr** [trueshiba/CS120-demo#16]
Lines 2-5 have semicolons, causing them to break future code.

Steps to Reproduce
Edit the semicolons from the code.

Expected Behavior
Expected the rgb colors to be converted to hex.

Actual Behavior A clear and concise description of what actually happened.
The code broke due to the extra semicolons.

Screenshots If applicable, add screenshots to help explain the issue/bug.

Possible Solution If you have any suggestions for a possible solution, please include them here.
Remove the semicolons.

Related Issues Are there any related issues? If so, please link to them here.
Nope.

Priority How critical is this issue/bug? Low, medium, or high priority?
High, the code will not run until it is fixed.

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
Easy to reproduce since semicolons can easily be added.

Impact What is the impact of this issue/bug? Low, medium, or high?
High, it breaks the code.

**Comment by mishwilso** [comment]
Extermination Complete, semicolons aren't a problem in this program. It would still run with the semicolons since python ignores them :)
