### ISSUE TITLE
remove_duplicates.py

### ISSUE THREAD

**Issue by trueshiba** [trueshiba/CS120-demo#17]
**Description:** 
Line 5 empty variable declaration

**Steps:**
1. Run program
2. Get runtime error

**Expected:**
unique_arr is looking for a declaration because of the = sign

**Actual:**
No value is provided, error occurs

**Screenshot**
![image](https://user-images.githubusercontent.com/107582031/226474944-31e066ac-3b58-48be-9930-523918f0f2d9.png)

**Additional Info:**
OS: Windows
Browser: Chrome

**Comment by Skye-Smith** [comment]
set unique_arr to a copy of arr on line 5
