### ISSUE TITLE
rgb_to_hex.py Wrong Number

### ISSUE THREAD

**Issue by agilpatr** [trueshiba/CS120-demo#19]
On line 2 the 255 was changed to 256.

Steps to Reproduce
Deleted the 255
Replace it with 256

Expected Behavior A clear and concise description of what you expected to happen.
I expected the code to run with range of 255.

Actual Behavior A clear and concise description of what actually happened.
It broke probably, or at least had the wrong output.

Screenshots If applicable, add screenshots to help explain the issue/bug.

Possible Solution If you have any suggestions for a possible solution, please include them here.
Change the 256 back to a 255.

Related Issues Are there any related issues? If so, please link to them here.
Nope.

Priority How critical is this issue/bug? Low, medium, or high priority?
Medium I'd say.

Reproducibility How often can this issue/bug be reproduced? Always, sometimes, or random?
Often because it's easy to put in the wrong number.

Impact What is the impact of this issue/bug? Low, medium, or high?
Medium.

**Comment by mishwilso** [comment]
Extermination Complete, number has been changed to 255
