### ISSUE TITLE
Missing Quotations

### ISSUE THREAD

**Issue by Skye-Smith** [trueshiba/CS120-demo#8]
The quotes to make date-time a string in line 9 of datetime_convert.cc

expected behavior: the program runs

actual behavior: program throws error on line 9

OS: Windows 10
Browser: firefox

possible solutions: add the required quotations

priority: high, program cannot run without solving the issue

reproducibility: always an issue, 100% reproducible

impact: high, program cannot run with bug

**Comment by trueshiba** [comment]
Fixed the issue. there are quotation marks now.
