### ISSUE TITLE
Typo in variable name

### ISSUE THREAD

**Issue by Skye-Smith** [trueshiba/CS120-demo#9]
typo in variable name on line 10 of datetime_convert.cc

expected behavior: the program runs

actual behavior: program throws error on line 10

OS: Windows 10
Browser: firefox

possible solutions: change vartiable name to match previous declaration

priority: high, program cannot run without solving the issue

reproducibility: always an issue, 100% reproducible

impact: high, program cannot run with bug in program

**Comment by trueshiba** [comment]
changed line 12 to be date_str instead of date_sr
